LampShade_Projects/ServiceHost/Areas/Administration/Pages/Accounts/Role/Create.cshtml.cs
using AccountManagement.Application.Contract.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ServiceHost.Areas.Administration.Pages.Accounts.Role
{
    public class CreateModel : PageModel
    {
        [BindProperty]
        public CreateRole Command { get; set; }
        private readonly IRoleApplication _application;

        public CreateModel(IRoleApplication application)
        {
            _application = application;
        }

        public void OnGet()
        {
        }

        public IActionResult OnPost()
        {
             _application.Create(Command);
            return RedirectToPage("Index");
        }
    }
}

LampShade_Projects/ServiceHost/Areas/Administration/Pages/Accounts/Role/Edit.cshtml.cs
using _0_Framework.Infrastucture;
using AccountManagement.Application.Contract.Role;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Accounts.Role
{
    public class EditModel : PageModel
    {
        [BindProperty]
        public EditRole Command { get; set; }

        public List<SelectListItem> Permissions = new List<SelectListItem>();
        private readonly IRoleApplication _application;
        private readonly IEnumerable<IPermissionExposer> _permissionsExposer;
        public EditModel(IRoleApplication application, IEnumerable<IPermissionExposer> permissionsExposer)
        {
            _application = application;
            _permissionsExposer = permissionsExposer;
        }

        public void OnGet(long id)
        {
           Command = _application.GetDetails(id);

           var permission = new List<PermissionDto>();
           foreach (var exposer in _permissionsExposer)
           {
               var exposerPermission = exposer.Expose();
               foreach (var (key,value) in exposerPermission)
               {
                   permission.AddRange(value);
                   var group = new SelectListGroup()
                   {
                       Name = key
                   };
                   foreach (var permissions in value)
                   {
                       var item = new SelectListItem(permissions.Name, permissions.Code.ToString())
                       {
                           Group = group
                       };

                       if (Command.MapedPermissions.Any(x => x.Code == permissions.Code))
                       {
                           item.Selected = true;
                       }

                       Permissions.Add(item);

                   }
               }
           }
        }
        public IActionResult OnPost()
        {
            _application.Edit(Command);
            return RedirectToPage("Index");
        }
    }
}

LampShade_Projects/ServiceHost/Areas/Administration/Pages/Blog/Article/Create.cshtml.cs
using BlogManagement.Application.Contract.Article;
using BlogManagement.Application.Contract.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Blog.Article
{
    public class CreateModel : PageModel
    {
        [BindProperty]
        public CreateArticle Article { get; set; }
        private readonly IArticleApplication _application;

        public SelectList ArticleCategories;
        private readonly IArticleCategoryApplication _articleCategory;

        public CreateModel(IArticleApplication application, IArticleCategoryApplication articleCategory)
        {
            _application = application;
            _articleCategory = articleCategory;
        }

        public void OnGet()
        {
            ArticleCategories = new SelectList(_articleCategory.GetArticleCategories(), "Id", "Name");
        }

        public IActionResult OnPost()
        {
            _application.Create(Article);
            return RedirectToPage("./Index");
        }
    }
}

LampShade_Projects/ServiceHost/Areas/Administration/Pages/Blog/Article/Edit.cshtml.cs
using BlogManagement.Application.Contract.Article;
using BlogManagement.Application.Contract.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ServiceHost.Areas.Administration.Pages.Blog.Article
{
    public class EditModel : PageModel
    {
        [BindProperty] public EditArticle Article { get; set; }
        private readonly IArticleApplication _application;

        public SelectList ArticleCategories;
        private readonly IArticleCategoryApplication _category;

        public EditModel(IArticleApplication application, IArticleCategoryApplication category)
        {
            _application = application;
            _category = category;
        }

        public void OnGet(long id)
        {
            Article = _application.GetDetails(id);
            ArticleCategories = new SelectList(_category.GetArticleCategories(), "Id", "Name");
        }

        public IActionResult OnPost()
        {
            _application.Edit(Article);
            return RedirectToPage("./Index");
        }
    }
}

LampShade_Projects/ServiceHost/Areas/Administration/Pages/Shop/Order/Index.cshtml.cs
using AccountManagement.Application.Contract.Account;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopManagement.Application.Contracts.Order;

namespace ServiceHost.Areas.Administration.Pages.Shop.Order
{
    //[Authorize(Roles = "3,5")]
    public class IndexModel : PageModel
    {
        public OrderSearchModel SearchModel;
        public List<OrderViewModel> Orders;
        public SelectList Accounts;

        private readonly IOrderApplication _orderApplication;
        private readonly IAccountApplication _accountApplication;

        public IndexModel(IOrderApplication orderApplication, IAccountApplication accountApplication)
        {
            _orderApplication = orderApplication;
            _accountApplication = accountApplication;
        }

        public void OnGet(OrderSearchModel searchModel)
        {
            Accounts = new SelectList(_accountApplication.GetList(), "Id", "Fullname");
            Orders = _orderApplication.Search(searchModel);
        }

        public IActionResult OnGetConfirm(long id)
        {
            _orderApplication.PaymentSucceeded(id, 0);
            return RedirectToPage("./Index");
        }

        public IActionResult OnGetCancel(long id)
        {
            _orderApplication.Cancel(id);
            return RedirectToPage("./Index");
        }

        public IActionResult OnGetItems(long orderId)
        {
           var items = _orderApplication.GetItems(orderId);
           return Partial("Items", items);
        }

    }
}

LampShade_Projects/ServiceHost/Areas/Administration/Pages/Shop/Product/Index.cshtml.cs
using _0_Framework.Infrastucture;
using _0_Framework.Permission;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopManagement.Application.Contracts.Product;
using ShopManagement.Application.Contracts.ProductCategory;

namespace ServiceHost.Areas.Administration.Pages.Shop.Product
{
    //[Authorize(Roles = "3,5")]
    public class IndexModel : PageModel
    {
        [TempData] public string Messsage { get; set; }

        public ProductSearchModel SearchModel;
        public List<ProductViewModel> ProductView;
        private readonly IProductApplication _productApplication;

        public SelectList Category;
        private readonly IProductCategoryApplication _application;

        public IndexModel(IProductCategoryApplication application, IProductApplication productApplication)
        {
            _application = application;
            _productApplication = productApplication;
        }

        [NeedsPermission(ShopPermission.ListProduct)]
        public void OnGet(ProductSearchModel SearchModel)
        { 
           Category = new SelectList(_application.GetProductCategory(),"Id","Name");
           ProductView = _productApplication.Search(SearchModel);
        }

        public IActionResult OnGetCreate()
        {
            var command = new CreateProduct
            {
                Category = _application.GetProductCategory()
            };
            return Partial("./Create",command);
        }

        [NeedsPermission(ShopPermission.CreateProduct)]
        public JsonResult OnPostCreate(CreateProduct command)
        {
           var result =  _productApplication.Create(command);
           return new JsonResult(result);
        }

        public IActionResult OnGetEdit(long id)
        {
            var product = _productApplication.GetDetails(id);
            product.Category = _application.GetProductCategory();
            return Partial("./Edit", product);
        }

        [NeedsPermission(ShopPermission.EditProduct)]
        public JsonResult OnPostEdit(EditProduct command)
        {
            var result = _productApplication.Edit(command);
            return new JsonResult(result);
        }

    }
}

LampShade_Projects/ServiceHost/Areas/Administration/Pages/Shop/ProductCategory/Index.cshtml.cs
using _0_Framework.Infrastucture;
using _0_Framework.Permission;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShopManagement.Application.Contracts.ProductCategory;

namespace ServiceHost.Areas.Administration.Pages.Shop.ProductCategory
{
    [Authorize(Roles = "3,5")]
    public class IndexModel : PageModel
    {
        public ProductCategorySearchModel SearchModel;
        public List<ProductCategoryViewModel> CategoryViewModels;

        private readonly IProductCategoryApplication _application;

        public IndexModel(IProductCategoryApplication application)
        {
            _application = application;
        }

        [NeedsPermission(ShopPermission.ListProductCategory)]
        public void OnGet(ProductCategorySearchModel SearchModel)
        { 
           CategoryViewModels = _application.Search(SearchModel);
        }

        public IActionResult OnGetCreate()
        {
            return Partial("./Create", new CreateProductCategory());
        }
        
        [NeedsPermission(ShopPermission.CreateProductCategory)]
        public JsonResult OnPostCreate(CreateProductCategory command)
        {
           var result =  _application.Create(command);
           return new JsonResult(result);
        }

        public IActionResult OnGetEdit(long id)
        {
           var productCategory = _application.GetDetails(id);
            return Partial("./Edit", productCategory);
        }
        
        [NeedsPermission(ShopPermission.EditProductCategory)]
        public JsonResult OnPostEdit(EditProductCategory command)
        {
            var result = _application.Edit(command);
            return new JsonResult(result);
        }
    }
}

LampShade_Projects/ServiceHost/Areas/Administration/Pages/Shop/ProductPicture/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopManagement.Application.Contracts.Product;
using ShopManagement.Application.Contracts.ProductPicture;
using ShopManagement.Domain.ProductPictureAgg;

namespace ServiceHost.Areas.Administration.Pages.Shop.ProductPicture
{
    public class IndexModel : PageModel
    {
        [TempData] public string Messsage { get; set; }

        public ProductPictureSearchModel SearchModel;
        public List<ProductPictureViewModel> ProductPictureView;
        private readonly IProductPictureApplication _pictureApplication;

        public SelectList Product;
        private readonly IProductApplication _application;

        public IndexModel(IProductApplication application, IProductPictureApplication pictureApplication)
        {
            _application = application;
            _pictureApplication = pictureApplication;
        }

        public void OnGet(ProductPictureSearchModel SearchModel)
        { 
           Product = new SelectList(_application.GetProducts(),"Id","Name");
           ProductPictureView = _pictureApplication.Search(SearchModel);
        }

        public IActionResult OnGetCreate()
        {
            var command = new CreateProductPicture
            {
                ProductView = _application.GetProducts()
            };
            return Partial("./Create", command);
        }
        public JsonResult OnPostCreate(CreateProductPicture command)
        {
           var result = _pictureApplication.Create(command);
           return new JsonResult(result);
        }

        public IActionResult OnGetEdit(long id)
        {
            var productPicture = _pictureApplication.GetDetails(id);
            productPicture.ProductView = _application.GetProducts();
            return Partial("./Edit", productPicture);
        }
        public JsonResult OnPostEdit(EditProductPicture command)
        {
            var result = _pictureApplication.Edit(command);
            return new JsonResult(result);
        }

        public RedirectToPageResult OnGetRemove(long id)
        {
           var result = _pictureApplication.Remove(id);
           if (result.IsSuccedded)
           {
               return RedirectToPage("./Index");
           }
           else
           {
               Messsage = result.Message;
           }
           return RedirectToPage("./Index");
        }
        public RedirectToPageResult OnGetRestore(long id)
        {
            var result = _pictureApplication.Restore(id);
            if (result.IsSuccedded)
            {
                return RedirectToPage("./Index");
            }
            else
            {
                Messsage = result.Message;
            }
            return RedirectToPage("./Index");
        }
    }
}

LampShade_Projects/ServiceHost/Areas/Administration/Pages/Shop/Slide/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ShopManagement.Application.Contracts.Slide;

namespace ServiceHost.Areas.Administration.Pages.Shop.Slide
{
    public class IndexModel : PageModel
    {
        [TempData] public string Messsage { get; set; }
        public List<SlideViewModel> SlideView;

        private readonly ISlideApplication _application;

        public IndexModel(ISlideApplication application)
        {
            _application = application;
        }

        public void OnGet()
        {
            SlideView = _application.GetList();
        }

        public IActionResult OnGetCreate()
        {
            var create = new CreateSlide();
            return Partial("./Create",create);
        }
        public JsonResult OnPostCreate(CreateSlide command)
        {
           var result = _application.Create(command);
           return new JsonResult(result);
        }

        public IActionResult OnGetEdit(long id)
        {
            var edit = _application.GetDetails(id);
            return Partial("./Edit", edit);
        }
        public JsonResult OnPostEdit(EditSlide command)
        {
            var result = _application.Edit(command);
            return new JsonResult(result);
        }

        public RedirectToPageResult OnGetRemove(long id)
        {
           var result = _application.Remove(id);
           if (result.IsSuccedded)
           {
               return RedirectToPage("./Index");
           }
           else
           {
               Messsage = result.Message;
           }
           return RedirectToPage("./Index");
        }
        public RedirectToPageResult OnGetRestore(long id)
        {
            var result = _application.Restore(id);
            if (result.IsSuccedded)
            {
                return RedirectToPage("./Index");
            }
            else
            {
                Messsage = result.Message;
            }
            return RedirectToPage("./Index");
        }
    }
}

LampShade_Projects/ServiceHost/Areas/Administration/Pages/Shop/ProductPicture/Create.cshtml
@model ShopManagement.Application.Contracts.ProductPicture.CreateProductPicture
@{
}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ایجاد عکس محصول جدید</h4>
</div>


<form asp-page="./Index" asp-page-handler="Create"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="ProductId" class="control-label">محصول</label>
                    <select class="form-control" asp-items='new SelectList(Model.ProductView, "Id", "Name")' asp-for="ProductId">
                        <option value="0">محصول</option>
                    </select>
                    <span asp-validation-for="ProductId" class="error"></span>
                </div>
            </div>
        </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="Picture" class="control-label">عکس</label>
                    <input type="file" class="form-control" asp-for="Picture" accept="image/*">
                    <span asp-validation-for="Picture" class="error"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureAlt" class="control-label">Alt</label>
                    <input type="text" class="form-control" asp-for="PictureAlt">
                    <span asp-validation-for="PictureAlt" class="error"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="PictureTitle" class="control-label">عنوان</label>
                    <input type="text" class="form-control" asp-for="PictureTitle">
                    <span asp-validation-for="PictureTitle" class="error"></span>
                </div>
            </div>
        </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ایجاد</button>
    </div>
</form>

LampShade_Projects/ServiceHost/Areas/Administration/Pages/Shop/ProductPicture/Edit.cshtml
@model ShopManagement.Application.Contracts.ProductPicture.EditProductPicture
@{
}
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title">ویرایش عکس محصول : @Model.Picture</h4>
</div>


<form asp-page="./Index" asp-page-handler="Edit"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="ProductId" class="control-label">محصول</label>
                    <select class="form-control" asp-items='new SelectList(Model.ProductView, "Id", "Name")' asp-for="ProductId">
                        <option value="0">محصول</option>
                    </select>
                    <span asp-validation-for="ProductId" class="error"></span>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label asp-for="Picture" class="control-label">عکس</label>
                <input type="file" class="form-control" asp-for="Picture" accept="image/*">
                <span asp-validation-for="Picture" class="error"></span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label asp-for="PictureAlt" class="control-label">Alt</label>
                <input type="text" class="form-control" asp-for="PictureAlt">
                <span asp-validation-for="PictureAlt" class="error"></span>
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label asp-for="PictureTitle" class="control-label">عنوان</label>
                <input type="text" class="form-control" asp-for="PictureTitle">
                <span asp-validation-for="PictureTitle" class="error"></span>
            </div>
        </div>
    </div>
    <input type="hidden" asp-for="Id" value="@Model.Id"/>
    <div class="modal-footer">
        <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
        <button type="submit" class="btn btn-info waves-effect waves-light">ویرایش</button>
    </div>
</form>

LampShade_Projects/ServiceHost/Areas/Administration/Pages/Shop/ProductPicture/Index.cshtml
@page
@model IndexModel
@{
}

@{
    Layout = "Shared/_AdminLayout";
    ViewData["title"] = "مدیریت عکس محصولات";
}

<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title pull-right">@ViewData["title"]</h4>
        <p class="pull-left">
            <a class="btn btn-success btn-lg" href="#showmodal=@Url.Page("./Index", "Create")">ایجاد عکس محصول جدید</a>
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">جستجو در عکس محصولات</h3>
            </div>
            <div class="panel-body">
                <form class="form-inline" role="form" method="get">
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.ProductId"></label>
                        <select class="form-control" asp-items="Model.Product" asp-for="SearchModel.ProductId" placeholder="نام محصول">
                            <option value="0">محصول</option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-success waves-effect waves-light m-l-10">جستجو</button>
                    <a class="btn btn-primary waves-effect waves-light m-l-10" asp-page="./Index">مشاهده همه</a>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row" id="ProductCategoriesDiv">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">لیست عکس محصولات</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>عکس</th>
                                    <th>نام محصولات</th>
                                    <th>وضعیت</th>
                                    <th>عملیات</th>
                                    <th>تاریخ تولید</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.ProductPictureView)
                                {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>
                                            <img src="~/ProductPictures/@item.Picture" style="width: 70px; height: 70px" />
                                        </td>
                                        <td>@item.Products</td>
                                        <td class="text-center">
                                            @if (!item.IsRemove)
                                            {
                                                <i class="fa fa-check fa-3x text-success"></i>
                                            }
                                            else
                                            {
                                                <i class="fa fa-remove fa-3x text-danger"></i>
                                            }
                                        </td>
                                        <td>@item.CreationDate</td>
                                        <td>
                                            <a class="btn btn-warning waves-effect waves-light m-b-5"
                                               href="#showmodal=@Url.Page("./Index", "Edit", new { id = item.Id})">
                                                <i class="fa fa-edit"></i> ویرایش
                                            </a>
                                            @if (!item.IsRemove)
                                            {
                                                <a class="btn btn-danger waves-effect waves-light m-b-5" 
                                                   asp-page="./Index" asp-page-handler="Remove" asp-route-id="@item.Id">حذف!</a>
                                            }
                                            else
                                            {
                                                <a class="btn btn-success waves-effect waves-light m-b-5" 
                                                   asp-page="./Index" asp-page-handler="Restore"asp-route-id="@item.Id">فعال سازی!</a>
                                            }
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/adminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/adminTheme/assets/datatables/dataTables.bootstrap.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#datatable').dataTable();
        });
    </script>
}